2020-01-06 22:33:41,369 ERROR: Exception on /user/Nestor [GET] [in C:\Users\54911\Anaconda3\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\54911\Documents\micron\app\routes.py", line 91, in user
    return render_template('user.html', user=user, posts=posts)
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\54911\Anaconda3\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\54911\Anaconda3\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\54911\Anaconda3\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\54911\Anaconda3\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\54911\Documents\micron\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\54911\Documents\micron\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\54911\Documents\micron\app\templates\base.html", line 49, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\54911\Documents\micron\app\templates\user.html", line 25, in block "app_content"
    {% include '_post.html' %}
  File "C:\Users\54911\Documents\micron\app\templates\_post.html", line 13, in top-level template code
    said {{ moment(post.timestamp).fromNow() }}:
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask_moment.py", line 133, in fromNow
    return self._render("fromNow(%s)" % int(no_suffix), refresh)
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask_moment.py", line 123, in _render
    t = self._timestamp_as_iso_8601(self.timestamp)
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask_moment.py", line 120, in _timestamp_as_iso_8601
    return timestamp.strftime('%Y-%m-%dT%H:%M:%S' + tz)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'timestamp'
2020-01-06 22:37:51,280 ERROR: Exception on /user/Nestor [GET] [in C:\Users\54911\Anaconda3\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\54911\Documents\micron\app\routes.py", line 91, in user
    return render_template('user.html', user=user, posts=posts)
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\54911\Anaconda3\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\54911\Anaconda3\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\54911\Anaconda3\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\54911\Anaconda3\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\54911\Documents\micron\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\54911\Documents\micron\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\54911\Documents\micron\app\templates\base.html", line 49, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\54911\Documents\micron\app\templates\user.html", line 25, in block "app_content"
    {% include '_post.html' %}
  File "C:\Users\54911\Documents\micron\app\templates\_post.html", line 13, in top-level template code
    said {{ moment(post.timestamp).fromNow() }}:
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask_moment.py", line 133, in fromNow
    return self._render("fromNow(%s)" % int(no_suffix), refresh)
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask_moment.py", line 123, in _render
    t = self._timestamp_as_iso_8601(self.timestamp)
  File "C:\Users\54911\Anaconda3\lib\site-packages\flask_moment.py", line 120, in _timestamp_as_iso_8601
    return timestamp.strftime('%Y-%m-%dT%H:%M:%S' + tz)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'timestamp'
